version: "3.3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=synergyway
      - POSTGRES_USER=pykulytsky
      - POSTGRES_PASSWORD=synergyway16
  backend:
    build: ./backend
    command: poetry run prod
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    container_name: backend
  frontend:
    build: ./frontend
    command: npm run start 
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    container_name: frontend
